### ISSUE TITLE
Unable to search by SKU in Catalog view

### ISSUE THREAD

**Issue by stuartmtm** [episerver/Foundation#168]
**Describe the bug**
When logged in as an editor going to commerce/catlog I am unable to search by SKU (code on variant) but I am able to search for the code from products 

**To Reproduce**
1. Go to Commerce / Catalog
2. Enter P-41071811 in the search box in the catalog navigation bar
3. You will see the product returned as a search result (Luke Cotton Coat)
4. Enter SKU-41071811 in the search box in teh catalog navigation bar
5. The variant will not be returned

**Expected behavior**
Expect to be able to search the catalog by variants

**Screenshots**
![image](https://user-images.githubusercontent.com/54805128/68476536-d7bf3f00-0222-11ea-8527-3eedbafae09d.png)

**Comment by lunchin** [comment]
Can you try again, I fixed this when looking into another issue as well.

**Comment by shgreig** [comment]
I'm still seeing this on the latest commit, do I need to force through any scheduled tasks?

**Comment by lunchin** [comment]
Probably easiest to create a demo index and test.  The one supplied by default is constantly getting rebuilt I guess,

**Comment by lunchin** [comment]
Please ignore PR reference, I made a mistake and supposedly cannot be removed in GitHub once referenced.

**Comment by shgreig-mtm** [comment]
I've created a new find index and rebuilt, I'm still seeing the same issue.
Is the catalog search even configured to use find at the moment?

**Comment by lunchin** [comment]
Sorry I was testing the catalog asset pane search and added a new search provider to search the nested skus in the product.  Looking into why it is not being used on the left side search as well.
